import_google_font:
  default: true
  description: When unchecked the theme will no longer include Google's Muli font. This is useful if you want to define your own font for the theme via theme component.
default_light:
  default: false
  description: When checked the theme will show the light theme as default for new visitors.
sidebar_dark_light_switch:
  default: false
  description: IF this component is installed (https://meta.discourse.org/t/dark-light-mode-toggle/215585) and you set this to true, you can toggle between your Dark and Light Color Palette.
